// Kroger store section mapping
export const STORE_SECTIONS: Record<string, string[]> = {
  Produce: [
    "lettuce",
    "tomato",
    "cucumber",
    "onion",
    "garlic",
    "potato",
    "carrot",
    "celery",
    "pepper",
    "apple",
    "banana",
    "orange",
    "lemon",
    "lime",
    "berry",
    "berries",
    "strawberry",
    "grape",
    "melon",
    "avocado",
    "mushroom",
    "spinach",
    "kale",
    "broccoli",
    "cauliflower",
    "zucchini",
    "squash",
    "green onion",
    "cherry tomato",
  ],
  "Meat & Seafood": [
    "chicken",
    "beef",
    "pork",
    "turkey",
    "fish",
    "salmon",
    "shrimp",
    "steak",
    "ground beef",
    "sausage",
    "bacon",
    "ham",
    "chicken breast",
    "thigh",
  ],
  "Dairy & Eggs": [
    "milk",
    "cheese",
    "yogurt",
    "butter",
    "cream",
    "egg",
    "eggs",
    "sour cream",
    "cottage cheese",
    "half and half",
    "dairy milk",
    "almond milk",
    "oat milk",
    "noosa",
    "lil noosas",
  ],
  "Frozen Foods": [
    "ice cream",
    "frozen",
    "pizza",
    "frozen vegetables",
    "frozen fruit",
    "frozen dinner",
    "popsicle",
    "frozen berries",
  ],
  Bakery: [
    "bread",
    "bagel",
    "roll",
    "rolls",
    "bun",
    "croissant",
    "muffin",
    "donut",
    "cake",
    "tortilla",
    "pita",
    "bagel bags",
  ],
  "Pantry & Canned Goods": [
    "rice",
    "pasta",
    "bean",
    "beans",
    "soup",
    "cereal",
    "oatmeal",
    "flour",
    "sugar",
    "canned",
    "tomato sauce",
    "broth",
    "stock",
    "campbell",
    "cannellini beans",
    "chickpea",
    "lentil",
    "chili bean",
  ],
  "Condiments & Sauces": [
    "ketchup",
    "mustard",
    "mayo",
    "mayonnaise",
    "hot sauce",
    "soy sauce",
    "olive oil",
    "vegetable oil",
    "vinegar",
    "salad dressing",
    "bbq sauce",
    "salsa",
    "canola oil",
    "sesame oil",
    "avocado oil",
    "coconut oil",
    "honey",
    "jam",
    "jelly",
    "peanut butter",
  ],
  International: [
    "tofu",
    "miso",
    "curry",
    "sushi",
    "ramen",
    "noodles",
    "kimchi",
    "tahini",
    "shawarma",
    "naan",
  ],
  Snacks: [
    "chip",
    "chips",
    "cracker",
    "cookie",
    "candy",
    "chocolate",
    "popcorn",
    "pretzel",
    "nut",
    "nuts",
    "granola",
    "trail mix",
  ],
  Beverages: [
    "water",
    "juice",
    "soda",
    "coffee",
    "tea",
    "beer",
    "wine",
    "sparkling",
  ],
  "Household & Cleaning": [
    "paper towel",
    "toilet paper",
    "tissue",
    "kleenex",
    "detergent",
    "soap",
    "shampoo",
    "dish soap",
    "cleaning",
    "trash bag",
    "laundry",
    "tide",
    "tide pods",
  ],
  Other: [],
};

// Order sections as they appear in a typical Kroger store
export const SECTION_ORDER = [
  "Produce",
  "Bakery",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Frozen Foods",
  "Pantry & Canned Goods",
  "International",
  "Condiments & Sauces",
  "Snacks",
  "Beverages",
  "Household & Cleaning",
  "Other",
];

// Color mapping for each store section
export const SECTION_COLORS: Record<string, { bg: string; text: string; border: string; darkBg: string; darkText: string; darkBorder: string }> = {
  Produce: {
    bg: "bg-emerald-100",
    text: "text-emerald-700",
    border: "border-emerald-400",
    darkBg: "dark:bg-emerald-900/30",
    darkText: "dark:text-emerald-400",
    darkBorder: "dark:border-emerald-600",
  },
  Bakery: {
    bg: "bg-amber-100",
    text: "text-amber-700",
    border: "border-amber-400",
    darkBg: "dark:bg-amber-900/30",
    darkText: "dark:text-amber-400",
    darkBorder: "dark:border-amber-600",
  },
  "Meat & Seafood": {
    bg: "bg-red-100",
    text: "text-red-700",
    border: "border-red-400",
    darkBg: "dark:bg-red-900/30",
    darkText: "dark:text-red-400",
    darkBorder: "dark:border-red-600",
  },
  "Dairy & Eggs": {
    bg: "bg-blue-100",
    text: "text-blue-700",
    border: "border-blue-400",
    darkBg: "dark:bg-blue-900/30",
    darkText: "dark:text-blue-400",
    darkBorder: "dark:border-blue-600",
  },
  "Frozen Foods": {
    bg: "bg-cyan-100",
    text: "text-cyan-700",
    border: "border-cyan-400",
    darkBg: "dark:bg-cyan-900/30",
    darkText: "dark:text-cyan-400",
    darkBorder: "dark:border-cyan-600",
  },
  "Pantry & Canned Goods": {
    bg: "bg-orange-100",
    text: "text-orange-700",
    border: "border-orange-400",
    darkBg: "dark:bg-orange-900/30",
    darkText: "dark:text-orange-400",
    darkBorder: "dark:border-orange-600",
  },
  "Condiments & Sauces": {
    bg: "bg-yellow-100",
    text: "text-yellow-700",
    border: "border-yellow-400",
    darkBg: "dark:bg-yellow-900/30",
    darkText: "dark:text-yellow-400",
    darkBorder: "dark:border-yellow-600",
  },
  International: {
    bg: "bg-purple-100",
    text: "text-purple-700",
    border: "border-purple-400",
    darkBg: "dark:bg-purple-900/30",
    darkText: "dark:text-purple-400",
    darkBorder: "dark:border-purple-600",
  },
  Snacks: {
    bg: "bg-pink-100",
    text: "text-pink-700",
    border: "border-pink-400",
    darkBg: "dark:bg-pink-900/30",
    darkText: "dark:text-pink-400",
    darkBorder: "dark:border-pink-600",
  },
  Beverages: {
    bg: "bg-teal-100",
    text: "text-teal-700",
    border: "border-teal-400",
    darkBg: "dark:bg-teal-900/30",
    darkText: "dark:text-teal-400",
    darkBorder: "dark:border-teal-600",
  },
  "Household & Cleaning": {
    bg: "bg-slate-100",
    text: "text-slate-700",
    border: "border-slate-400",
    darkBg: "dark:bg-slate-900/30",
    darkText: "dark:text-slate-400",
    darkBorder: "dark:border-slate-600",
  },
  Other: {
    bg: "bg-gray-100",
    text: "text-gray-700",
    border: "border-gray-400",
    darkBg: "dark:bg-gray-900/30",
    darkText: "dark:text-gray-400",
    darkBorder: "dark:border-gray-600",
  },
};

// Color palette for AI-proposed dynamic sections
const DYNAMIC_SECTION_COLORS = [
  { bg: "bg-violet-100", text: "text-violet-700", border: "border-violet-400", darkBg: "dark:bg-violet-900/30", darkText: "dark:text-violet-400", darkBorder: "dark:border-violet-600" },
  { bg: "bg-rose-100", text: "text-rose-700", border: "border-rose-400", darkBg: "dark:bg-rose-900/30", darkText: "dark:text-rose-400", darkBorder: "dark:border-rose-600" },
  { bg: "bg-indigo-100", text: "text-indigo-700", border: "border-indigo-400", darkBg: "dark:bg-indigo-900/30", darkText: "dark:text-indigo-400", darkBorder: "dark:border-indigo-600" },
  { bg: "bg-lime-100", text: "text-lime-700", border: "border-lime-400", darkBg: "dark:bg-lime-900/30", darkText: "dark:text-lime-400", darkBorder: "dark:border-lime-600" },
  { bg: "bg-fuchsia-100", text: "text-fuchsia-700", border: "border-fuchsia-400", darkBg: "dark:bg-fuchsia-900/30", darkText: "dark:text-fuchsia-400", darkBorder: "dark:border-fuchsia-600" },
  { bg: "bg-sky-100", text: "text-sky-700", border: "border-sky-400", darkBg: "dark:bg-sky-900/30", darkText: "dark:text-sky-400", darkBorder: "dark:border-sky-600" },
];

/** Returns colors for a section -- fixed colors for known sections, deterministic palette pick for dynamic ones */
export function getSectionColors(section: string): { bg: string; text: string; border: string; darkBg: string; darkText: string; darkBorder: string } {
  if (SECTION_COLORS[section]) return SECTION_COLORS[section];
  // Deterministic hash based on char codes
  let hash = 0;
  for (let i = 0; i < section.length; i++) {
    hash = (hash + section.charCodeAt(i)) * 31;
  }
  return DYNAMIC_SECTION_COLORS[Math.abs(hash) % DYNAMIC_SECTION_COLORS.length];
}

export function categorizeItem(itemName: string): string {
  const lowerItem = itemName.toLowerCase();

  for (const [section, keywords] of Object.entries(STORE_SECTIONS)) {
    if (section === "Other") continue;

    for (const keyword of keywords) {
      if (lowerItem.includes(keyword)) {
        return section;
      }
    }
  }

  return "Other";
}
