name: AIsleList
options:
  bundleIdPrefix: com.aislelist
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    DEVELOPMENT_TEAM: RKFCF9LE9G

targets:
  AIsleList:
    type: application
    platform: iOS
    sources:
      - path: AIsleListApp.swift
      - path: ContentView.swift
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Utilities
    info:
      path: Resources/Info.plist
      properties:
        CFBundleDisplayName: AIsle List
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSCameraUsageDescription: AIsle List uses your camera to photograph handwritten grocery lists
        NSPhotoLibraryUsageDescription: AIsle List accesses your photos to read handwritten grocery lists
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aislelist.app
    entitlements:
      path: Resources/AIsleList.entitlements
