// Kroger store section mapping
export const STORE_SECTIONS: Record<string, string[]> = {
  Produce: [
    "lettuce",
    "tomato",
    "cucumber",
    "onion",
    "garlic",
    "potato",
    "carrot",
    "celery",
    "pepper",
    "apple",
    "banana",
    "orange",
    "lemon",
    "lime",
    "berry",
    "berries",
    "strawberry",
    "grape",
    "melon",
    "avocado",
    "mushroom",
    "spinach",
    "kale",
    "broccoli",
    "cauliflower",
    "zucchini",
    "squash",
    "green onion",
    "cherry tomato",
  ],
  "Meat & Seafood": [
    "chicken",
    "beef",
    "pork",
    "turkey",
    "fish",
    "salmon",
    "shrimp",
    "steak",
    "ground beef",
    "sausage",
    "bacon",
    "ham",
    "chicken breast",
    "thigh",
  ],
  "Dairy & Eggs": [
    "milk",
    "cheese",
    "yogurt",
    "butter",
    "cream",
    "egg",
    "eggs",
    "sour cream",
    "cottage cheese",
    "half and half",
    "dairy milk",
    "almond milk",
    "oat milk",
  ],
  "Frozen Foods": [
    "ice cream",
    "frozen",
    "pizza",
    "frozen vegetables",
    "frozen fruit",
    "frozen dinner",
    "ice",
    "popsicle",
    "frozen berries",
  ],
  Bakery: [
    "bread",
    "bagel",
    "roll",
    "bun",
    "croissant",
    "muffin",
    "donut",
    "cake",
    "tortilla",
    "pita",
    "bagel bags",
  ],
  "Pantry & Canned Goods": [
    "rice",
    "pasta",
    "bean",
    "beans",
    "soup",
    "cereal",
    "oatmeal",
    "flour",
    "sugar",
    "canned",
    "tomato sauce",
    "broth",
    "stock",
    "campbell",
    "cannellini beans",
    "chickpea",
    "lentil",
    "chili bean",
  ],
  "Condiments & Sauces": [
    "ketchup",
    "mustard",
    "mayo",
    "mayonnaise",
    "hot sauce",
    "soy sauce",
    "olive oil",
    "vegetable oil",
    "vinegar",
    "salad dressing",
    "bbq sauce",
    "salsa",
    "oil",
    "honey",
    "jam",
    "jelly",
    "peanut butter",
  ],
  International: [
    "tofu",
    "miso",
    "curry",
    "sushi",
    "ramen",
    "noodles",
    "kimchi",
    "tahini",
    "shawarma",
    "naan",
    "miso soup",
    "shawarma tofu",
    "costco noodles",
  ],
  Snacks: [
    "chip",
    "chips",
    "cracker",
    "cookie",
    "candy",
    "chocolate",
    "popcorn",
    "pretzel",
    "nut",
    "nuts",
    "granola",
    "trail mix",
    "noosa",
    "lil noosas",
  ],
  Beverages: [
    "water",
    "juice",
    "soda",
    "coffee",
    "tea",
    "beer",
    "wine",
    "sparkling",
  ],
  "Household & Cleaning": [
    "paper towel",
    "toilet paper",
    "tissue",
    "kleenex",
    "detergent",
    "soap",
    "shampoo",
    "dish soap",
    "cleaning",
    "trash bag",
    "laundry",
    "tide",
    "tide pods",
  ],
  Other: [],
};

// Order sections as they appear in a typical Kroger store
export const SECTION_ORDER = [
  "Produce",
  "Bakery",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Frozen Foods",
  "Pantry & Canned Goods",
  "International",
  "Condiments & Sauces",
  "Snacks",
  "Beverages",
  "Household & Cleaning",
  "Other",
];

export function categorizeItem(itemName: string): string {
  const lowerItem = itemName.toLowerCase();

  for (const [section, keywords] of Object.entries(STORE_SECTIONS)) {
    if (section === "Other") continue;

    for (const keyword of keywords) {
      if (lowerItem.includes(keyword)) {
        return section;
      }
    }
  }

  return "Other";
}
